### ISSUE TITLE
to be able to row bind: need to transform previous column abbrevName_fish to new column FishSpecies

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/nes-lter-fish-diet#4]

**Comment by sbeaulieu** [comment]
considering either 'mutate case when' or adding onto fish lookup table

**Comment by sbeaulieu** [comment]
add onto fish lookup table from categorical variables template FishSpecies. put new version fish lookup table into current fish-diet repo

**Comment by sbeaulieu** [comment]
added into repo a new version fish lookup table with columns abbrevName_fish and FishSpecies to be able to match previous and current versions data

**Comment by joefutrelle** [comment]
Using `plyr::mapvalues`
