### ISSUE TITLE
update data submodule

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/nes-lter-fish-diet#9]
new versions of data tables have been pushed to [Sarah's GitHub](https://github.com/glancysg/ForageFish_EDI)

**Comment by joefutrelle** [comment]
https://github.com/WHOIGit/nes-lter-fish-diet/commit/821077ac657c3153d6da49e5bb2bdd736df272d5

**Comment by joefutrelle** [comment]
Rmd runs without issues
